forumCSGO/config/routes.rb
Rails.application.routes.draw do
  get 'control_users/index'

  get 'home/index'
  root "home#index"
  devise_for :users
  resources :articles

  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

forumCSGO/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

forumCSGO/app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
end

forumCSGO/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  
end

forumCSGO/app/models/user.rb
class User < ApplicationRecord
  enum role: [:normal_user, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

forumCSGO/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit
  protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
    def user_not_authorized
      flash[:notice] = "Você não tem permissão para fazer essa ação."
      redirect_to(request.referrer || root_path)
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:first_name, :last_name, :username, :birthday, :email, :password, :remember_me)
    end
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email, :password, :remember_me)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:first_name, :last_name, :username, :birthday, :about, :email, :password, :current_password, :remember_me)
    end
  end
end

forumCSGO/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  include ArticlesHelper
  def index
    @articles = Article.all
  end
  def new
    @article = Article.new
  end
  def show
    @article = Article.find(params[:id])
  
  end
  def create
    @article = Article.new(article_params)
    @article.title = params[:article][:title]
    @article.body = params[:article][:body]
    @article.username = current_user.username
    @article.date = Time.now.strftime("%Y/%m/%d")
    @article.save

    redirect_to article_path(@article)
  end
  def edit
    @article = Article.find(params[:id])
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end
end

forumCSGO/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment].permit(:name, :body))
    redirect_to article_path(@article)
  end
  def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy

      redirect_to article_path(@article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body,:id, :article_id)
  end
end

forumCSGO/app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
    authorize @users
  end
end

forumCSGO/app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
  end
end

forumCSGO/app/helpers/application_helper.rb
module ApplicationHelper
end

forumCSGO/app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body)
  end
  
end

forumCSGO/app/helpers/comments_helper.rb
module CommentsHelper
end

forumCSGO/app/helpers/control_users_helper.rb
module ControlUsersHelper
end

forumCSGO/app/helpers/home_helper.rb
module HomeHelper
end

forumCSGO/app/views/articles/edit.html.erb
<h1>Editar o post</h1>

<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

forumCSGO/app/views/articles/index.html.erb
<h1 align="center">Tópicos</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>

<%= link_to "Criar um novo tópico", new_article_path, class: "new_article" %>

forumCSGO/app/views/articles/new.html.erb
<h1>Criar um novo artigo</h1>

<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title, "Título do tópico" %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body, "Texto" %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Criar tópico"%>
  </p>
<% end %>

forumCSGO/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<p><%= @article.username %></p>
<p><%= @article.date %></p>

<% if policy(@article).index? %>
<%= link_to "Deletar", article_path(@article), method: :delete, data: {confirm: "Deseja deletar o post?"}%>
<% end %>
<% if (policy(@article).index?) || current_user == @article.username%>
<%= link_to "Editar", edit_article_path(@article) %>
<% end %>
<%= render 'comments/form' %>
<h3>Comentarios (<%= @article.comments.size %>)</h3>
<%= render @article.comments %>

forumCSGO/app/views/comments/_comment.html.erb
<div>
  <h4>Comentario feito por <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
</div>
<% if policy(@article).index? || current_user == @article.username %>
<p><%= link_to 'Delete', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?'} %></p>
<% end %>

forumCSGO/app/views/comments/_form.html.erb
<h3>Poste um comentario</h3>

<%= form_for([@article,@article.comments.build]) do |f| %>


    <p>
      <%= f.label :body, "Texto" %><br/>
      <%= f.text_area :body %>
    </p>
      <%= f.submit 'Enviar' %>
    </p>
<% end %>

forumCSGO/app/views/control_users/index.html.erb
<h1>Controle de Usuarios</h1>

<table align="center">
  <thread>
    <tr>
      <th align="center">ID</th>
      <th align="center">Email</th>
      <th align="center">Funcao</th>
    </tr>
  </thread>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td width="100", align="left"><%= user.id %></td>
      <td width="200", align="left"><%= user.email %></td>
      <td width="200", align="left"><%= user.role %></td>



    </tr>
  <% end %>
  </tbody>
</table>

forumCSGO/app/views/home/index.html.erb
<h1>Página Inicial</h1>

<% if user_signed_in? %>
<body>
<font size="5">Seja bem-vindo <%= current_user.username %></font>
<p><img src="csgo.png" style="width:800px;height:400px;"></p>
</body>
<% else %>
<body>
<font size="5">Seja bem-vindo visitante</font>
</body>
<% end %>

forumCSGO/app/views/layouts/_footer.html.erb
<div id="push"></div>
<footer class="footer navbar-fixed-bottom">
  <div class="container">
    <nav>
      <ul>
        Desenvolvido por João Pedro Martins e William Almeida
      </ul>
    </nav>
  </div>
</footer>

forumCSGO/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForumCSGO</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>
        <p class="flash", align="center"><%= flash.notice %></p>
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <%= link_to "FORUMCSGO", root_url, class: "navbar-brand" %>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <%= link_to "Ver tópicos", articles_path %>
                        </li>
                        <li>
                          <% if !user_signed_in? %>
                            <li><%= link_to "Entrar", new_user_session_path %></li>
                            <% end %>
                        </li>
                        <li>
                            <% if !user_signed_in? %>
                            <li><%= link_to "Cadastro", new_user_registration_path %></li>
                            <% end %>
                        </li>
                        <li>
                            <% if user_signed_in? %>
                            <li><%= link_to "Usuários", control_users_index_path %></li>
                            <% end %>
                        </li>
                        <li>
                            <% if user_signed_in? %>
                            <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
                            <% end %>
                        </li>
                        <li>
                            <% if user_signed_in? %>
                            <li><%= link_to "Painel de controle", edit_user_registration_path %></li>
                            <% end %>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>

        <!-- Page Content -->
        <div class="container">

            <div class="row">
                <div class="col-lg-12 text-center">
                  <%= yield %>


                </div>
            </div>
            <!-- /.row -->

        </div>

        <!-- /.container -->

        <style>body{padding-top:70px}</style>
        <!-- jQuery Version 1.11.1 -->
        <script src="js/jquery.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="js/bootstrap.min.js"></script>
        <%= render 'layouts/footer' %>


    </body>



    </html>

forumCSGO/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Entre", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Cadastre-se", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua senha?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>